export const routes = {
  initial: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  terms: '/terms',
  home: '/home',
  team: '/team',
  settings: '/settings',
  settingsHistory: '/settings/history',
  settingsDomain: '/settings/domain',
  settingsFooter: '/settings/footer',
  settingsAccount: '/settings/account',
  invite: (token = ':token') => `/invite/${token}`,
  publicLinkPage: (slug = ':slug') => `/p/${slug}`,
  publicPostPage: '/p/:slug/:postSlug',
  linkPages: {
    list: '/link-pages',
    /** First access after sign-up: opens the plans dialog. */
    welcome: '/link-pages?welcome=1',
    new: '/link-pages/new',
    edit: (id = ':id') => `/link-pages/${id}/edit`,
  },
  errors: {
    broken: '/error/broken',
    notFound: '/error/not-found',
    internal: '/error/internal',
  },
};
